import { Module } from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';
import {
  Risk,
  RiskSchema,
  RiskAppetiteVersion,
  RiskAppetiteVersionSchema,
  Control,
  ControlSchema,
  ControlTest,
  ControlTestSchema,
  Deficiency,
  DeficiencySchema,
  TreatmentPlan,
  TreatmentPlanSchema,
  Incident,
  IncidentSchema,
  BcpPlan,
  BcpPlanSchema,
  BcpTest,
  BcpTestSchema,
  RtoRpo,
  RtoRpoSchema,
  CrisisContact,
  CrisisContactSchema,
  BiaProcess,
  BiaProcessSchema,
  VendorResilience,
  VendorResilienceSchema,
  BcpIncident,
  BcpIncidentSchema,
  BcpReport,
  BcpReportSchema,
  BcpTestFinding,
  BcpTestFindingSchema,
  EmergingRisk,
  EmergingRiskSchema,
} from './schemas';
import { HrTeam, HrTeamSchema } from 'src/modules/hr/schemas/hr.schema';
import {
  Employee,
  EmployeeSchema,
} from 'src/modules/hr/schemas/employee.schema';
import {
  Vendor as CrmVendor,
  VendorSchema as CrmVendorSchema,
} from 'src/modules/crm/crm/schemas/vendor.schema';
import {
  RiskService,
  RiskAppetiteService,
  ControlService,
  TreatmentPlanService,
  IncidentService,
  BcpService,
  EmergingRiskService,
  TestPlanService,
  DeficiencyService,
} from './services';
import {
  RiskController,
  RiskAppetiteController,
  ControlController,
  TreatmentPlanController,
  IncidentController,
  BcpController,
  EmergingRiskController,
} from './controllers';

@Module({
  imports: [
    MongooseModule.forFeature([
      { name: Risk.name, schema: RiskSchema },
      { name: RiskAppetiteVersion.name, schema: RiskAppetiteVersionSchema },
      { name: Control.name, schema: ControlSchema },
      { name: ControlTest.name, schema: ControlTestSchema },
      { name: Deficiency.name, schema: DeficiencySchema },
      { name: TreatmentPlan.name, schema: TreatmentPlanSchema },
      { name: Incident.name, schema: IncidentSchema },
      { name: BcpPlan.name, schema: BcpPlanSchema },
      { name: BcpTest.name, schema: BcpTestSchema },
      { name: RtoRpo.name, schema: RtoRpoSchema },
      { name: CrisisContact.name, schema: CrisisContactSchema },
      { name: BiaProcess.name, schema: BiaProcessSchema },
      { name: VendorResilience.name, schema: VendorResilienceSchema },
      { name: BcpIncident.name, schema: BcpIncidentSchema },
      { name: BcpReport.name, schema: BcpReportSchema },
      { name: BcpTestFinding.name, schema: BcpTestFindingSchema },
      { name: EmergingRisk.name, schema: EmergingRiskSchema },
      { name: HrTeam.name, schema: HrTeamSchema },
      { name: Employee.name, schema: EmployeeSchema },
      { name: CrmVendor.name, schema: CrmVendorSchema },
    ]),
  ],
  providers: [
    RiskService,
    RiskAppetiteService,
    ControlService,
    TreatmentPlanService,
    IncidentService,
    BcpService,
    EmergingRiskService,
    TestPlanService,
    DeficiencyService,
  ],
  controllers: [
    RiskController,
    RiskAppetiteController,
    ControlController,
    TreatmentPlanController,
    IncidentController,
    BcpController,
    EmergingRiskController,
  ],
  exports: [
    RiskService,
    RiskAppetiteService,
    ControlService,
    TreatmentPlanService,
    IncidentService,
    BcpService,
    EmergingRiskService,
    TestPlanService,
    DeficiencyService,
  ],
})
export class RiskModule {}
