import { Module } from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';
import {
  Employee,
  EmployeeAttendance,
  EmployeeAttendanceSchema,
  EmployeeSchema,
} from './schemas/employee.schema';
import {
  EmployeeService,
  LeaveService,
  AttendanceService,
  OnboardingService,
  PayrollCalculationService,
  PayrollPolicyService,
  EmployeeLoanService,
  ExchangeRateService,
  PayrollRunService,
  PayslipTemplateService,
  PayrollExportService,
  PerformanceScoringService,
  KpiTemplateService,
  FrameworkService,
  ReviewCycleService,
  PerformanceReviewService,
  CandidateService,
  OffboardingService,
  SuccessionPlanService,
  RequisitionTypeService,
  RequisitionService,
} from './services';
import { User, UserSchema } from '../auth/schemas/user.schema';
import { EmailService } from '../../common/utils/mailing/email.service';
import {
  HrTenantController,
  HrEmployeeController,
  HrOnboardingController,
  PayrollPolicyController,
  EmployeeLoanController,
  PayrollRunController,
  PayslipTemplateController,
  CandidateController,
  OffboardingController,
  SuccessionPlanController,
  RequisitionController,
  RequisitionTypeController,
} from './controllers';
import {
  LeaveRequest,
  LeaveRequestSchema,
  LeavePolicy,
  LeavePolicySchema,
  HrTeam,
  HrLocation,
  HrTeamSchema,
  HrLocationSchema,
  OnboardingDocument,
  OnboardingDocumentSchema,
  EmployeeOnboarding,
  EmployeeOnboardingSchema,
  PayrollPolicy,
  PayrollPolicySchema,
  EmployeeLoan,
  EmployeeLoanSchema,
  PayrollRun,
  PayrollRunSchema,
  Payslip,
  PayslipSchema,
  PayslipTemplate,
  PayslipTemplateSchema,
  ExchangeRateSnapshot,
  ExchangeRateSnapshotSchema,
  KpiTemplate,
  KpiTemplateSchema,
  CompetencyFramework,
  CompetencyFrameworkSchema,
  ValuesFramework,
  ValuesFrameworkSchema,
  ReviewCycle,
  ReviewCycleSchema,
  PerformanceReview,
  PerformanceReviewSchema,
  Candidate,
  CandidateSchema,
  OffboardingRecord,
  OffboardingRecordSchema,
  SuccessionPlan,
  SuccessionPlanSchema,
  RequisitionType,
  Requisition,
  RequisitionTypeSchema,
  RequisitionSchema,
} from './schemas';
import {
  FrameworkController,
  KpiTemplateController,
  PerformanceReviewController,
  ReviewCycleController,
} from './controllers/performance-tenant.controller';

@Module({
  imports: [
    MongooseModule.forFeature([
      { name: Employee.name, schema: EmployeeSchema },
      { name: User.name, schema: UserSchema },
      { name: LeaveRequest.name, schema: LeaveRequestSchema },
      { name: LeavePolicy.name, schema: LeavePolicySchema },
      { name: EmployeeAttendance.name, schema: EmployeeAttendanceSchema },
      { name: HrTeam.name, schema: HrTeamSchema },
      { name: HrLocation.name, schema: HrLocationSchema },
      { name: OnboardingDocument.name, schema: OnboardingDocumentSchema },
      { name: EmployeeOnboarding.name, schema: EmployeeOnboardingSchema },
      { name: PayrollPolicy.name, schema: PayrollPolicySchema },
      { name: EmployeeLoan.name, schema: EmployeeLoanSchema },
      { name: PayrollRun.name, schema: PayrollRunSchema },
      { name: Payslip.name, schema: PayslipSchema },
      { name: PayslipTemplate.name, schema: PayslipTemplateSchema },
      { name: ExchangeRateSnapshot.name, schema: ExchangeRateSnapshotSchema },
      { name: KpiTemplate.name, schema: KpiTemplateSchema },
      { name: CompetencyFramework.name, schema: CompetencyFrameworkSchema },
      { name: ValuesFramework.name, schema: ValuesFrameworkSchema },
      { name: ReviewCycle.name, schema: ReviewCycleSchema },
      { name: PerformanceReview.name, schema: PerformanceReviewSchema },
      { name: Candidate.name, schema: CandidateSchema },
      { name: OffboardingRecord.name, schema: OffboardingRecordSchema },
      { name: SuccessionPlan.name, schema: SuccessionPlanSchema },
      { name: RequisitionType.name, schema: RequisitionTypeSchema },
      { name: Requisition.name, schema: RequisitionSchema },
    ]),
  ],
  controllers: [
    HrTenantController,
    HrEmployeeController,
    HrOnboardingController,
    PayrollPolicyController,
    EmployeeLoanController,
    PayrollRunController,
    PayslipTemplateController,
    KpiTemplateController,
    FrameworkController,
    ReviewCycleController,
    PerformanceReviewController,
    CandidateController,
    OffboardingController,
    SuccessionPlanController,
    RequisitionController,
    RequisitionTypeController,
  ],
  providers: [
    EmployeeService,
    EmailService,
    LeaveService,
    AttendanceService,
    OnboardingService,
    PayrollCalculationService,
    PayrollPolicyService,
    EmployeeLoanService,
    ExchangeRateService,
    PayrollRunService,
    PayslipTemplateService,
    PayrollExportService,
    PerformanceScoringService,
    KpiTemplateService,
    FrameworkService,
    ReviewCycleService,
    PerformanceReviewService,
    CandidateService,
    OffboardingService,
    SuccessionPlanService,
    RequisitionTypeService,
    RequisitionService,
  ],
  exports: [
    EmployeeService,
    LeaveService,
    AttendanceService,
    OnboardingService,
    PayrollRunService,
    PerformanceReviewService,
  ],
})
export class HrModule {}
